# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :candidate_filing do
    election_txt "MyString"
    election_year 1
    office_group "MyString"
    candidate_source_id 1
    office "MyString"
    candidate_office "MyString"
    candidate_filing_source_id 1
    file_method_indicator "MyString"
    filetype_descr "MyString"
    party_affiliation "MyString"
    major_party_indicator "MyString"
    candidate_ballot_name "MyString"
    candidate_occupation "MyString"
    candidate_education_background "MyText"
    candidate_occupation_background "MyText"
    candidate_credentials "MyString"
    previous_government_background "MyString"
    judge_incumbent_indicator "MyString"
    qlf_indicator "MyString"
    filed_date "2014-10-07"
    file_fee_refund_date "2014-10-07"
    withdraw_date "2014-10-07"
    withdraw_reason "MyString"
    pttn_file_date "2014-10-07"
    pttn_sgnr_rqd_nbr "MyString"
    pttn_signr_filed_nbr "MyString"
    pttn_cmplt_date "2014-10-07"
    ballot_order_nbr "MyString"
    prfx_name_cd "MyString"
    first_name "MyString"
    middle_name "MyString"
    last_name "MyString"
    suffix_name "MyString"
    title "MyString"
    mailing_address_line_1 "MyString"
    mailing_address_line_2 "MyString"
    mailing_city "MyString"
    mailing_state "MyString"
    mailing_zip_code "MyString"
    mailing_zip_plus_four "MyString"
    residence_address_line_1 "MyString"
    residence_address_line_2 "MyString"
    residence_city "MyString"
    residence_state "MyString"
    residence_zip_code "MyString"
    residence_zip_plus_four "MyString"
    home_phone "MyString"
    cell_phone "MyString"
    fax_phone "MyString"
    email "MyString"
    work_phone "MyString"
    web_address "MyString"
  end
end
