json.(@campaign_finance_transaction, :id, :source_id, :original_id,
      :transaction_date,
      :transaction_status,
      :amount,
      :aggregate_amount,
      :filed_date,
      :filer_id,
      :filer,
      :contributor_payee,
      :city,
      :state,
      :zip)
